# Generated by Django 3.0.8 on 2020-07-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0002_auto_20200714_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
