# Generated by Django 3.0.8 on 2020-07-16 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0002_auto_20200716_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 17, 8, 25, 388822, tzinfo=utc)),
        ),
    ]
