# Generated by Django 3.0.8 on 2020-07-16 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0003_auto_20200716_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
