# Generated by Django 3.0.8 on 2020-07-15 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0004_auto_20200715_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date_like',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 12, 42, 47, 682504, tzinfo=utc)),
        ),
    ]
