# Generated by Django 3.0.8 on 2020-07-15 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0005_like_date_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_like',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 13, 21, 14, 258064, tzinfo=utc)),
        ),
    ]
