# Generated by Django 3.0.8 on 2020-07-15 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0006_auto_20200715_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date_like',
        ),
        migrations.AddField(
            model_name='like',
            name='date_liked',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 17, 24, 46, 509179, tzinfo=utc)),
        ),
    ]
