# Generated by Django 3.0.8 on 2020-07-15 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0007_auto_20200715_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 19, 5, 29, 482290, tzinfo=utc)),
        ),
    ]
