# Generated by Django 3.0.8 on 2020-07-15 20:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_api', '0009_auto_20200715_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 20, 20, 35, 344205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
