# Generated by Django 3.0.8 on 2020-07-15 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0010_auto_20200715_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='last_login',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_liked',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 20, 34, 17, 774866, tzinfo=utc)),
        ),
    ]
